apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: observability
  namespace: vela-system
spec:
  components:
    - name: grafana-registration
      type: helm
      properties:
        chart: chart
        version: 0.0.7
        repoType: git
        url: https://github.com/JooKS-me/grafana-registration
        releaseName: grafana-registration
